services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./memory.db:/app/memory.db
    # Bind the model component directly to the app service
    models:
      - chatbot_llm

models:
  chatbot_llm:
    # Set the OCI registry path of your target model
    model: ai/gemma4:12B