FROM docker.io/ollama/ollama:0.20.0
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install sudo -y && sudo apt update
RUN sudo apt-get update && sudo apt-get install -y --no-install-recommends \
   ca-certificates \
   curl \
   gnupg2
RUN curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
  && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
    sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
RUN sudo apt-get update
RUN sudo apt-get install -y nvidia-container-toolkit
EXPOSE 11434
# Pre-Install llama2
ARG MODEL_NAME
RUN nohup bash -c "ollama serve &" && sleep 5 && ollama pull $MODEL_NAME
CMD ["serve"]